language: python
python:
  - "3.8"
 
# command to install dependencies
install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - export PATH=$PATH:$HOME/.poetry/bin
  - pip install -r requirements.txt
  - poetry install --no-dev

# command to run tests
script:
  - behave tests/features
