---
version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=borrowborrow
      - POSTGRES_DB=borrowborrow
    ports:
      - 5433:5432